version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
        #command: gunicorn dj_dastore.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn dj_dastore.wsgi:application --bind 0.0.0.0:8000 --log-level debug
      #user: '1000:1000'
    volumes:
      - /mnt/nfs/static_cdn:/home/dj_dastore/web/static_cdn
      - /mnt/nfs/media_cdn:/home/dj_dastore/web/media_cdn
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db1_prod
    environment:
      DJANGO_SETTINGS_MODULE: dj_dastore.settings.production
  nginx:
      build: ./nginx
      restart: always
      volumes:
        - static_cdn:/home/dj_dastore/web/static_cdn
        - media_cdn:/home/dj_dastore/web/media_cdn
        - /home/topaze/certs:/etc/nginx/certs
      ports:
        - 80:80
        - 443:443
      depends_on:
        - web
  db1_prod:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    depends_on:
      - db1_prod
    env_file:
      - ./.env.prod.db
  autopgbackup:
    image: rogersik/autopostgresqlbackup:latest
    env_file:
      - ./.env.prod
    environment:
      - CRON_LOG_LEVEL=0
      - CRON_SCHEDULE=5 4 * * *
      - LATEST=yes
    volumes:
     - /opt/docker/foobar/db_dumps:/backups
     - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db1_prod
  stripe:
    image: stripe/stripe-cli:v1.15.0
    command: ["listen", "--api-key", "${STRIPE_TEST_SECRET_KEY}", "--forward-to", "web:8000/stripe/webhook/"]
    depends_on:
      - web
    env_file:
      - ./.env.prod
    environment:
      - STRIPE_DEVICE_NAME=djstripe_docker
volumes:
  media_cdn:
  static_cdn:
  postgres_data:
