version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn dj_dastore.wsgi:application --bind 0.0.0.0:8000
    user: '1000:1000'
    ports:
      - 8000:8000
    volumes:
      - ./static_cdn:/home/dj_dastore/web/static_cdn
      - ./media_cdn:/home/dj_dastore/web/media_cdn
    env_file:
      - ./.env.prod
    depends_on:
      - db1_prod
    environment:
      DJANGO_SETTINGS_MODULE: dj_dastore.settings.production
  db1_prod:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  stripe:
    image: stripe/stripe-cli:v1.7.4
    network_mode: host  
    command: listen --api-key=$STRIPE_TEST_SECRET_KEY --forward-to http://web:8000/stripe/webhook/
    volumes:
      - ./.env.prod:/usr/src/dj_dastore/.env.prod
    depends_on:
      - web
    environment:
      - /usr/src/dj_dastore/.env.prod
      - STRIPE_DEVICE_NAME=djstripe_docker
volumes:
  postgres_data:
